In [1]:
import numpy as np

In [3]:
Vector1=np.array(range(3,29))
Vector1

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28])

In [5]:
Vector2=np.array([0,1,2,3,4,0,1,2,3,4])
Vector2

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [8]:
Vector2.sort()

In [9]:
Vector2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])